# Generated by Django 3.1.7 on 2021-03-15 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('symbol', models.CharField(max_length=4)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('asset_buy_quantity', models.DecimalField(decimal_places=8, max_digits=14)),
                ('asset_sell_quantity', models.DecimalField(decimal_places=8, max_digits=14)),
                ('fee_quantity', models.DecimalField(decimal_places=8, max_digits=14)),
                ('broker', models.CharField(max_length=20)),
                ('exchange', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('asset_buy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_buy', to='tracker.asset')),
                ('asset_sell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_sell', to='tracker.asset')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee', to='tracker.asset')),
            ],
        ),
    ]
