# Generated by Django 3.1.7 on 2021-03-16 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20210316_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('CO', 'Commodity'), ('CR', 'Crypto'), ('FI', 'Fiat'), ('FU', 'Fund'), ('ST', 'Stock')], max_length=2),
        ),
        migrations.AlterField(
            model_name='trade',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='broker', to='tracker.broker'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange', to='tracker.exchange'),
        ),
    ]
