# Generated by Django 3.1.7 on 2021-03-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210316_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='asset_buy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_buy', to='tracker.asset', verbose_name='buy'),
        ),
    ]
