# Generated by Django 3.1.7 on 2021-03-20 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20210320_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='asset_buy_quantity',
            field=models.DecimalField(decimal_places=8, max_digits=14, verbose_name='buy quantity'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='asset_sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_sell', to='tracker.asset', verbose_name='sell'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='asset_sell_quantity',
            field=models.DecimalField(decimal_places=8, max_digits=14, verbose_name='sell quantity'),
        ),
    ]
