# Generated by Django 3.1.7 on 2021-03-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20210320_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('asset_quantity', models.DecimalField(decimal_places=8, max_digits=14, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=8, max_digits=14)),
                ('posting_type', models.CharField(choices=[('B', 'Buy'), ('F', 'Fee'), ('S', 'Sell')], max_length=1)),
                ('open_quantity', models.DecimalField(decimal_places=8, max_digits=14, verbose_name='open')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assetAccount_asset', to='tracker.asset', verbose_name='asset')),
                ('price_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assetAccount_priceAsset', to='tracker.asset', verbose_name='price asset')),
            ],
        ),
    ]
