# Generated by Django 3.1.7 on 2021-03-27 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_assetaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetaccount',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='assetaccount',
            name='price_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assetAccount_priceAsset', to='tracker.asset', verbose_name='price asset'),
        ),
    ]
