# Generated by Django 3.1.7 on 2021-03-27 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20210327_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaccount',
            name='trade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assetAccount_trade', to='tracker.trade'),
        ),
    ]
